name: flutter_application_1
description: "Alaa Smart App - 2026"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  file_picker: ^8.0.0
  audioplayers: ^5.2.1
  url_launcher: ^6.2.5
  video_player: ^2.8.6
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - audio/sky.wav
    - audio/rain.wav
    - audio/river.wav
    - audio/forest.wav
    - audio/fire.mp3
